INSERT INTO organisations (name, email, phone_no) VALUES ('LBG', 'lbg@lbg.com', '12345,6789');
insert into organisations (name, email, phone_no) values ('Atos', 'atos@atos.com', '805768,3558');
insert into organisations (name, email, phone_no) values ('M&S', 'm&s@m&s.com', '305735,4302');
insert into organisations (name, email, phone_no) values ('CFC', 'cfc@cfc.com', '815564,3538');
insert into organisations (name, email, phone_no) values ('Invesco', 'invesco@invesco.com', '564125,7748');
insert into organisations (name, email, phone_no) values ('Mercator', 'mercator@mercator.com', '224497,1649');

insert into events (location, start_date_time, end_date_time, organisation_id, event_type) values ('Nar''yan-Mar', '2023-01-29 19:00:00', '2023-01-29 23:00:00', 6, 'GOLF');
insert into events (location, start_date_time, end_date_time, organisation_id, event_type) values ('Huayuanli', '2023-04-13 19:00:00', '2023-04-13 23:00:00', 1, 'DINNER');
insert into events (location, start_date_time, end_date_time, organisation_id, event_type) values ('Nanqi', '2023-05-04 19:00:00', '2023-05-04 23:00:00', 2, 'GOLF');
insert into events (location, start_date_time, end_date_time, organisation_id, event_type) values ('Pringgabaya', '2023-06-20 19:00:00', '2023-06-20 23:00:00', 3, 'DRINKING');
insert into events (location, start_date_time, end_date_time, organisation_id, event_type) values ('Nueva Arica', '2023-05-16 19:00:00', '2023-05-16 23:00:00', 4, 'CINEMA');
insert into events (location, start_date_time, end_date_time, organisation_id, event_type) values ('Tomiya', '2023-07-22 19:00:00', '2023-07-22 23:00:00', 1, 'DINNER');
insert into events (location, start_date_time, end_date_time, organisation_id, event_type) values ('Ban Phaeo', '2023-07-14 19:00:00', '2023-07-14 23:00:00', 1, 'CINEMA');
insert into events (location, start_date_time, end_date_time, organisation_id, event_type) values ('Shuangxiqiao', '2023-03-11 19:00:00', '2023-03-11 23:00:00', 1, 'BOWLING');
insert into events (location, start_date_time, end_date_time, organisation_id, event_type) values ('Qiubin', '2023-03-06 19:00:00', '2023-03-06 23:00:00', 5, 'DINNER');
insert into events (location, start_date_time, end_date_time, organisation_id, event_type) values ('Kadugannawa', '2023-04-02 19:00:00', '2023-04-02 23:00:00', 5, 'CINEMA');
insert into events (location, start_date_time, end_date_time, organisation_id, event_type) values ('Urung', '2023-02-14 19:00:00', '2023-02-14 23:00:00', 6, 'GOLF');
insert into events (location, start_date_time, end_date_time, organisation_id, event_type) values ('Neyagawa', '2022-12-22 19:00:00', '2022-12-22 23:00:00', 4, 'GOKARTING');
insert into events (location, start_date_time, end_date_time, organisation_id, event_type) values ('Psygansu', '2023-03-12 19:00:00', '2023-03-12 23:00:00', 6, 'GOKARTING');
insert into events (location, start_date_time, end_date_time, organisation_id, event_type) values ('Venëv', '2023-06-22 19:00:00', '2023-06-22 23:00:00', 6, 'DINNER');
insert into events (location, start_date_time, end_date_time, organisation_id, event_type) values ('Karlskoga', '2023-07-26 19:00:00', '2023-07-26 23:00:00', 6, 'GOLF');
insert into events (location, start_date_time, end_date_time, organisation_id, event_type) values ('Buenavista', '2023-03-14 19:00:00', '2023-03-14 23:00:00', 5, 'LUNCH');
insert into events (location, start_date_time, end_date_time, organisation_id, event_type) values ('São Paio de Seide', '2023-07-07 19:00:00', '2023-07-07 23:00:00', 4, 'GOKARTING');
insert into events (location, start_date_time, end_date_time, organisation_id, event_type) values ('Pasar', '2022-12-14 19:00:00', '2022-12-14 23:00:00', 2, 'GOLF');
insert into events (location, start_date_time, end_date_time, organisation_id, event_type) values ('Castelo', '2023-05-04 19:00:00', '2023-05-04 23:00:00', 5, 'DINNER');
insert into events (location, start_date_time, end_date_time, organisation_id, event_type) values ('Ōtsuki', '2022-12-21 19:00:00', '2022-12-21 23:00:00', 6, 'CINEMA');
insert into events (location, start_date_time, end_date_time, organisation_id, event_type) values ('Cantuk Kidul', '2023-04-12 19:00:00', '2023-04-12 23:00:00', 5, 'DINNER');
insert into events (location, start_date_time, end_date_time, organisation_id, event_type) values ('Los Cerrillos', '2023-02-19 19:00:00', '2023-02-19 23:00:00', 4, 'DRINKING');
insert into events (location, start_date_time, end_date_time, organisation_id, event_type) values ('Loma Bonita', '2023-02-27 19:00:00', '2023-02-27 23:00:00', 4, 'GOLF');
insert into events (location, start_date_time, end_date_time, organisation_id, event_type) values ('Bajo', '2022-12-19 19:00:00', '2022-12-19 23:00:00', 5, 'GOKARTING');
insert into events (location, start_date_time, end_date_time, organisation_id, event_type) values ('Cabanas de Viriato', '2023-06-17 19:00:00', '2023-06-17 23:00:00', 1, 'DRINKING');
insert into events (location, start_date_time, end_date_time, organisation_id, event_type) values ('Novopokrovka', '2023-06-07 19:00:00', '2023-06-07 23:00:00', 6, 'BOWLING');
insert into events (location, start_date_time, end_date_time, organisation_id, event_type) values ('Xiabaishi', '2023-05-23 19:00:00', '2023-05-23 23:00:00', 5, 'DINNER');
insert into events (location, start_date_time, end_date_time, organisation_id, event_type) values ('Dobrovo', '2023-07-09 19:00:00', '2023-07-09 23:00:00', 1, 'GOKARTING');
insert into events (location, start_date_time, end_date_time, organisation_id, event_type) values ('Pecatu', '2023-02-19 19:00:00', '2023-02-19 23:00:00', 3, 'DINNER');
insert into events (location, start_date_time, end_date_time, organisation_id, event_type) values ('Badajoz', '2023-05-31 19:00:00', '2023-05-31 23:00:00', 2, 'BOWLING');

insert into employees (user_name, organisation_id) values ('kbaudasso0', 2);
insert into employees (user_name, organisation_id) values ('jvanni1', 4);
insert into employees (user_name, organisation_id) values ('ddemitri2', 6);
insert into employees (user_name, organisation_id) values ('akirby3', 5);
insert into employees (user_name, organisation_id) values ('jshellshear4', 4);
insert into employees (user_name, organisation_id) values ('dlineen5', 2);
insert into employees (user_name, organisation_id) values ('ccarhart6', 1);
insert into employees (user_name, organisation_id) values ('gbattey7', 2);
insert into employees (user_name, organisation_id) values ('pnower8', 6);
insert into employees (user_name, organisation_id) values ('dmccowan9', 3);
insert into employees (user_name, organisation_id) values ('agreschika', 5);
insert into employees (user_name, organisation_id) values ('jdeganb', 2);
insert into employees (user_name, organisation_id) values ('kbelloc', 5);
insert into employees (user_name, organisation_id) values ('nbleythingd', 2);
insert into employees (user_name, organisation_id) values ('rduddelle', 6);
insert into employees (user_name, organisation_id) values ('bbredef', 5);
insert into employees (user_name, organisation_id) values ('glechelleg', 6);
insert into employees (user_name, organisation_id) values ('cjeannonh', 2);
insert into employees (user_name, organisation_id) values ('gmountstepheni', 1);
insert into employees (user_name, organisation_id) values ('gwinslowj', 3);
insert into employees (user_name, organisation_id) values ('csmowtonk', 6);
insert into employees (user_name, organisation_id) values ('jjenckesl', 2);
insert into employees (user_name, organisation_id) values ('wblomfieldm', 4);
insert into employees (user_name, organisation_id) values ('icreaseyn', 2);
insert into employees (user_name, organisation_id) values ('nrubinskyo', 3);
insert into employees (user_name, organisation_id) values ('apriddeyp', 1);
insert into employees (user_name, organisation_id) values ('jshickleq', 6);
insert into employees (user_name, organisation_id) values ('urodenborchr', 3);
insert into employees (user_name, organisation_id) values ('mdalgetys', 4);
insert into employees (user_name, organisation_id) values ('rtuffint', 6);

INSERT INTO venues (location, name, type) VALUES ('London', 'Slug and Lettuce', 'DRINKING');
insert into venues (location, name, type) values ('Northfield', 'GlaxoSmithKline Consumer Healthcare LP', 'DINNER');
insert into venues (location, name, type) values ('Schmedeman', 'Unifirst First Aid Corporation', 'LUNCH');
insert into venues (location, name, type) values ('Sutherland', 'BCM Ltd', 'GOLF');
insert into venues (location, name, type) values ('Magdeline', 'Roxane Laboratories, Inc', 'DRINKING');
insert into venues (location, name, type) values ('Stephen', 'ABC Compounding Co., Inc.', 'GOLF');
insert into venues (location, name, type) values ('Lakewood Gardens', 'Watson Pharma, Inc.', 'CINEMA');
insert into venues (location, name, type) values ('Dayton', 'Aurobindo Pharma Limited', 'CINEMA');
insert into venues (location, name, type) values ('Center', 'SHISEIDO AMERICAS CORPORATION', 'LUNCH');
insert into venues (location, name, type) values ('Straubel', 'Wal-Mart Stores Inc', 'DRINKING');
insert into venues (location, name, type) values ('Corben', 'Sandoz Inc', 'BOWLING');

--insert into employee_event_mapper (employee_id, event_id) values (9, 16);
--insert into employee_event_mapper (employee_id, event_id) values (8, 26);
--insert into employee_event_mapper (employee_id, event_id) values (25, 13);
--insert into employee_event_mapper (employee_id, event_id) values (28, 18);
--insert into employee_event_mapper (employee_id, event_id) values (12, 10);
--insert into employee_event_mapper (employee_id, event_id) values (22, 3);
--insert into employee_event_mapper (employee_id, event_id) values (11, 16);
--insert into employee_event_mapper (employee_id, event_id) values (2, 15);
--insert into employee_event_mapper (employee_id, event_id) values (29, 4);
--insert into employee_event_mapper (employee_id, event_id) values (3, 6);
--insert into employee_event_mapper (employee_id, event_id) values (10, 10);
--insert into employee_event_mapper (employee_id, event_id) values (8, 12);
--insert into employee_event_mapper (employee_id, event_id) values (6, 30);
--insert into employee_event_mapper (employee_id, event_id) values (13, 30);
--insert into employee_event_mapper (employee_id, event_id) values (13, 2);
--insert into employee_event_mapper (employee_id, event_id) values (16, 3);
--insert into employee_event_mapper (employee_id, event_id) values (4, 25);
--insert into employee_event_mapper (employee_id, event_id) values (10, 6);
--insert into employee_event_mapper (employee_id, event_id) values (13, 30);
--insert into employee_event_mapper (employee_id, event_id) values (12, 2);
--insert into employee_event_mapper (employee_id, event_id) values (14, 11);
--insert into employee_event_mapper (employee_id, event_id) values (29, 30);
--insert into employee_event_mapper (employee_id, event_id) values (28, 13);
--insert into employee_event_mapper (employee_id, event_id) values (24, 12);
--insert into employee_event_mapper (employee_id, event_id) values (30, 10);
--insert into employee_event_mapper (employee_id, event_id) values (4, 20);
--insert into employee_event_mapper (employee_id, event_id) values (17, 13);
--insert into employee_event_mapper (employee_id, event_id) values (11, 6);
--insert into employee_event_mapper (employee_id, event_id) values (18, 17);
--insert into employee_event_mapper (employee_id, event_id) values (7, 26);
--
--insert into venue_event_mapper (venue_id, event_id) values (6, 16);
--insert into venue_event_mapper (venue_id, event_id) values (8, 11);
--insert into venue_event_mapper (venue_id, event_id) values (4, 28);
--insert into venue_event_mapper (venue_id, event_id) values (9, 18);
--insert into venue_event_mapper (venue_id, event_id) values (3, 17);
--insert into venue_event_mapper (venue_id, event_id) values (10, 5);
--insert into venue_event_mapper (venue_id, event_id) values (2, 20);
--insert into venue_event_mapper (venue_id, event_id) values (1, 6);
--insert into venue_event_mapper (venue_id, event_id) values (1, 12);
--insert into venue_event_mapper (venue_id, event_id) values (5, 28);
--insert into venue_event_mapper (venue_id, event_id) values (3, 7);
--insert into venue_event_mapper (venue_id, event_id) values (3, 19);
--insert into venue_event_mapper (venue_id, event_id) values (1, 2);
--insert into venue_event_mapper (venue_id, event_id) values (3, 14);
--insert into venue_event_mapper (venue_id, event_id) values (1, 27);
--insert into venue_event_mapper (venue_id, event_id) values (4, 6);
--insert into venue_event_mapper (venue_id, event_id) values (8, 2);
--insert into venue_event_mapper (venue_id, event_id) values (1, 12);
--insert into venue_event_mapper (venue_id, event_id) values (11, 10);
--insert into venue_event_mapper (venue_id, event_id) values (4, 10);
--insert into venue_event_mapper (venue_id, event_id) values (5, 10);
--insert into venue_event_mapper (venue_id, event_id) values (6, 18);
--insert into venue_event_mapper (venue_id, event_id) values (4, 22);
--insert into venue_event_mapper (venue_id, event_id) values (6, 30);
--insert into venue_event_mapper (venue_id, event_id) values (6, 26);
--insert into venue_event_mapper (venue_id, event_id) values (7, 11);
--insert into venue_event_mapper (venue_id, event_id) values (6, 24);
--insert into venue_event_mapper (venue_id, event_id) values (8, 24);
--insert into venue_event_mapper (venue_id, event_id) values (8, 12);
--insert into venue_event_mapper (venue_id, event_id) values (3, 8);